name: Pokemon Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository abrufen
        uses: actions/checkout@v3

      - name: .NET Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Dependencies installieren
        run: dotnet restore

      - name: Code Format 端berpr端fen
        run: dotnet format --verify-no-changes

      - name: Code-Analyse durchf端hren
        run: dotnet build --configuration Release /p:EnableNETAnalyzers=true

      - name: Build Projekt
        run: dotnet build --configuration Release

      - name: Tests ausf端hren
        run: dotnet test --configuration Release

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Repository abrufen
        uses: actions/checkout@v3

      - name: .NET Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor App
        run: dotnet publish -c Release -o out

      - name: Deployment auf Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MeineMudBlazorApp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'out'
